export const corporateJokes: string[] = [
  "I told my boss three companies were after me, so he gave me a raise to stay. The other three were the electric, water, and gas company.",
  "My job is secure. No one else wants it.",
  "I'm not saying I hate my job, I'm just saying if I called in dead they wouldn't be able to prove otherwise for at least three days.",
  "Dear Monday, I don't like your attitude.",
  "Let's circle back on that after we synergize our bandwidth.",
  "I put the 'pro' in procrastinate and the 'gress' in progress meeting.",
  "Our KPI for today is Keep Pretending It's fine.",
  "I don't need an inspirational quote. I need coffee and a raise.",
  "Nothing says 'I have my life together' like unmuting yourself mid-sentence on a Zoom call.",
  "My favorite meeting is the one that gets cancelled.",
  "Low-hanging fruit? I can't even reach the tree.",
  "I'm on a seafood diet. I see food at the break room and eat it during the budget meeting.",
  "The only 'agile' thing about our sprint is how fast I run to lunch.",
  "I have a 'can-do' attitude about ending this meeting.",
  "Let's take this offline — said no one who actually wanted to solve the problem.",
  "My out-of-office reply is more honest than my performance review.",
  "I don't do mornings. I do 'aggressively caffeinated afternoons.'",
  "Reply-all is the corporate equivalent of a fire alarm.",
  "I'm not late, I'm running on 'flexible synergy time.'",
  "We don't have deadlines, we have 'suggested aspirational timelines.'",
  "My LinkedIn says 'thought leader.' My inbox says otherwise.",
  "Corporate wellness program: a stress ball and a smile.",
  "I put 'team player' on my resume. I meant fantasy football.",
  "Our brainstorm meetings mostly involve the storm and very little brain.",
  "I asked for a work-life balance. They gave me a hammock emoji in Slack.",
  "The best part of my job is the 'end' in 'weekend.'",
  "I don't skip leg day. I skip Monday meetings.",
  "Ah yes, another meeting that could've been a two-line email.",
  "My spirit animal is the auto-reply.",
  "I've mastered the art of nodding in meetings I stopped listening to ten minutes ago.",
  "Corporate ladder? I'm still looking for the first rung.",
  "Nothing boosts morale like a mandatory fun activity.",
  "I run on coffee, deadlines, and mild denial.",
  "My to-do list has a to-do list.",
  "We're not behind schedule, we're 'iterating in real time.'",
  "I gave 110% today. Unfortunately, my job only asked for 20%.",
  "The printer is down again. So is my will to live.",
  "Our team is like a family — dysfunctional but oddly loyal.",
  "I asked for feedback. I got a PowerPoint.",
  "My commute is shorter now. It's just from the bed to the desk.",
  "I've achieved inbox zero. It's called deleting everything.",
  "Every meeting should end with 'let's take that as an action item' — mine end with 'let's order lunch.'",
  "I'm allergic to Mondays. The rash is called 'existential dread.'",
  "My badge photo looks more alive than I feel at 9 a.m.",
  "We don't have a hierarchy. We have 'flat, collaborative confusion.'",
  "The Wi-Fi password here changes more often than our strategy.",
  "I don't need therapy. I need my manager to stop scheduling 4:45 p.m. meetings.",
  "Our onboarding process is basically 'good luck.'",
  "I've read the employee handbook. It's mostly fiction.",
  "Nothing says 'urgent' like an email marked urgent sent on a Friday at 5 p.m.",
  "I'm fluent in three languages: English, sarcasm, and corporate jargon.",
  "My favorite Excel formula is =QUIT().",
  "We call it a 'growth opportunity.' I call it unpaid overtime.",
  "I don't procrastinate, I prioritize aggressively — starting tomorrow.",
  "Our team-building exercise was mostly building resentment.",
  "I love deadlines. I love the whooshing sound they make as they fly by.",
  "The only thing agile about our workflow is how quickly it falls apart.",
  "My résumé says 'detail-oriented.' My desk says otherwise.",
  "I've perfected the 'thinking face' during meetings I've mentally left.",
  "We don't have a budget. We have 'creative constraints.'",
  "Nothing says trust like a manager who CCs your manager.",
  "My favorite office plant is the one that's actually plastic — like our optimism.",
  "I've been in 'final review' for three weeks. So has my sanity.",
  "The coffee machine has better uptime than our servers.",
  "I don't need a motivational poster. I need this meeting to end.",
  "We pivoted so many times this quarter I got dizzy.",
  "My inbox has more unread messages than my browser has open tabs — and that's saying something.",
  "Corporate speak translator: 'Let's touch base' means 'I forgot your name.'",
  "I said I'd have it done by end of day. I meant end of my career.",
  "Our all-hands meeting had zero hands raised and zero answers given.",
  "I'm not avoiding work, I'm 'strategically deprioritizing.'",
  "The office thermostat war is the only real competition here.",
  "My job title changed three times this year. My salary didn't notice.",
  "We don't have problems, we have 'opportunities for innovation.'",
  "I've mastered looking busy — it's my most transferable skill.",
  "Every Slack channel eventually becomes a GIF war.",
  "I asked what 'synergy' means. Nobody could tell me. That was the synergy.",
  "My calendar is so full I scheduled a meeting to find time for lunch.",
  "We don't miss deadlines, we 'extend the runway.'",
  "I'm on version 47 of this document. Nobody remembers what version 1 said.",
  "My standing desk mostly stands there while I sit on the floor.",
  "Half our meetings could be replaced by a single sticky note.",
  "I don't hate Mondays. I hate the meetings that come with them.",
  "Our five-year plan changes about every five weeks.",
  "I'm not ignoring your email, I'm 'processing it asynchronously.'",
  "The vending machine understands my needs better than HR does.",
  "I've achieved work-life balance: equal amounts of stress at both.",
  "Nothing unites a team like a shared hatred of the new scheduling software.",
  "My job would be perfect if it weren't for the actual work.",
  "We don't have a plan B. We have 'agile improvisation.'",
  "I read the fine print on my offer letter. It was mostly clip art.",
  "My favorite corporate buzzword is 'bandwidth,' mostly because I never have any.",
  "The meeting invite said 15 minutes. That was optimistic fiction.",
  "I've never met a status update that couldn't have been a thumbs-up emoji.",
  "Our brainstorming session produced one idea and four new meetings to discuss it.",
  "I don't need a raise. I need my emails answered before the heat death of the universe.",
  "The office motivational quote wall has never once motivated anyone.",
  "I put 'proactive' on my resume. I meant I proactively avoid extra meetings.",
  "Nothing says 'we value your feedback' like ignoring it in the next town hall.",
  "At this company, a 'quick call' is never quick and rarely a call — it's always a 45-minute video meeting.",
];
